local mymappings = {
  [']'] = {
    d = {
      '<cmd>lua vim.lsp.diagnostic.goto_next({popup_opts = {border = lvim.lsp.popup_border}})<cr>',
      'Next Diagnostic',
    },
    -- c = { "<cmd>lua require 'gitsigns'.next_hunk()<cr>", 'Next Hunk' },
    x = { [[<cmd>lua require('trouble').next({skip_groups=true, jump=true})<CR>]], 'Next Trouble' },
  },
  ['['] = {
    d = {
      '<cmd>lua vim.lsp.diagnostic.goto_prev({popup_opts = {border = lvim.lsp.popup_border}})<cr>',
      'Prev Diagnostic',
    },
    -- c = { "<cmd>lua require 'gitsigns'.prev_hunk()<cr>", 'Prev Hunk' },
    x = { [[<cmd>lua require('trouble').previous({skip_groups=true, jump=true})<CR>]], 'Prev Trouble' },
  },
  ['<C-w>'] = {
    m = 'Zoom',
    [' '] = { "<cmd>lua require('focus').focus_toggle()<cr>", 'FocusToggle' },
    -- e = "",
    -- t = "",
    -- b = "",
    -- a = "",
    -- d = "",
  },
  ['<C-y>'] = {},
  ['<C-p>'] = {},
  ['<C-s>'] = {},
  -- Must
  ['<C-z>'] = {},
  -- ["<C-a>"] = {},
  -- ["<C-x>"] = {},
  -- ["<C-f>"] = {},
  -- ["<C-b>"] = {},
  -- ["<C-n>"] = {},
  y = {
    c = {
      name = '+colorscheme',
      m = { "<cmd>lua require('material.functions').toggle_style()<cr>", 'Material' },
      c = { "<cmd>lua require('user.theme').toggle_style()<cr>", 'Style' },
    },
    o = {
      name = '+options',
      n = { '<cmd>setlocal number!<cr>', 'number' },
      r = { '<cmd>setlocal relativenumber!<cr>', 'relativenumber' },
      ['|'] = { '<cmd>setlocal cursorcolumn!<cr>', 'column' },
      ['-'] = { '<cmd>setlocal cursorline!<cr>', 'line' },
      l = { '<cmd>setlocal list!<cr>', 'list' },
      s = { '<cmd>setlocal spell!<cr>', 'spell' },
      w = { '<cmd>setlocal wrap!<cr>', 'wrap' },
      h = { '<cmd>set hls!<cr>', 'hightlight' },
      b = { [[:set background=<C-R>=&background == "dark" ? "light" : "dark"<CR><cr>]], 'background' },
      m = { [[:set mouse=<C-R>=&mouse == "a" ? "" : "a"<CR><cr>]], 'mouse' },
      M = { ':lua ToggleMouse()<cr>', 'mouse+' },
      f = { ':call FoldTextToggle()<cr>', 'hightlight' },
    },
  },
  [','] = {
    f = {
      name = '+fzf',
      [' '] = { "<cmd>lua require('fzf-lua').live_grep_resume()<CR>", 'Grep' },
      ['<C-q>'] = { "<cmd>lua require('fzf-lua').quickfix()<CR>", 'Quickfix' },
      ['<C-e>'] = { "<cmd>lua require('fzf-lua').loclist()<CR>", 'Loclist' },
      f = { "<cmd>lua require('fzf-lua').files()<CR>", 'Files' },
      b = { "<cmd>lua require('fzf-lua').buffers()<CR>", 'Buffers' },
      r = { "<cmd>lua require('fzf-lua').files_resume()<CR>", 'Resume' },
      m = { "<cmd>lua require('fzf-lua').oldfiles()<CR>", 'MRU' },
      l = { "<cmd>lua require('fzf-lua').blines()<CR>", 'Lines' },
      L = { "<cmd>lua require('fzf-lua').lines()<CR>", 'Lines' },
      T = { "<cmd>lua require('fzf-lua').tab()<CR>", 'Tab' },
      g = { "<cmd>lua require('fzf-lua').live_grep()<CR>", 'Grep' },
      s = { "<cmd>lua require('fzf-lua').grep()<CR>", 'Grep' },
      o = { "<cmd>lua require('fzf-lua').git_status()<CR>", 'Git Status' },
      c = { "<cmd>lua require('fzf-lua').git_commits()<CR>", 'Commits' },
      p = { "<cmd>lua require('fzf-lua').colorschemes()<CR>", 'Colorschemes' },
    },
    s = {
      name = '+seek',
      c = { '<cmd>Telescope cheat fd<cr>', 'Cheatsheet' },
      v = { '<cmd>Cheatsheet<cr>', 'Vim Cheatsheet' },
    },
  },
}

return mymappings
